server:
  port: 8080  # 端口配置
spring:
  datasource:  # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: ahu264657

mybatis:  # mybatis配置
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名和下划线命名的自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL日志